name: depi_final_project
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  auto_scroll_image: ^0.2.9-dev
  awesome_dialog: ^3.1.0
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  email_validator: ^3.0.0
  get: ^4.6.6
  path: ^1.9.0
  uuid: ^4.5.1
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  achievement_view: ^1.0.1
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.2
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.1.1


  flutter_screenutil: ^5.9.3
  google_sign_in: ^6.2.1
  scroll_loop_auto_scroll: ^0.0.2
  stylish_bottom_bar: ^1.1.0
  shared_preferences: ^2.3.2
  share_plus: ^10.0.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.4
  expandable: ^5.0.0
dev_dependencies:
  flutter_launcher_icons: ^0.14.1

  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logoapp.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

