// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_w2Hwuj1sWtQA3PbE8AzZK73l3Cb-g8',
    appId: '1:427220706549:web:24e3d1c21f10a5796e91bc',
    messagingSenderId: '427220706549',
    projectId: 'finalproject-30f96',
    authDomain: 'finalproject-30f96.firebaseapp.com',
    storageBucket: 'finalproject-30f96.appspot.com',
    measurementId: 'G-XCGMP7CY5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tOu_Z9cBixOvd7ywdb5UORW7Cy5njqQ',
    appId: '1:427220706549:android:94160166f7db6d9b6e91bc',
    messagingSenderId: '427220706549',
    projectId: 'finalproject-30f96',
    storageBucket: 'finalproject-30f96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2bA0ReRwJShN2pOvGaUO7Y3m3tacFieI',
    appId: '1:427220706549:ios:1a75a39024324dee6e91bc',
    messagingSenderId: '427220706549',
    projectId: 'finalproject-30f96',
    storageBucket: 'finalproject-30f96.appspot.com',
    androidClientId: '427220706549-2u95imrvdkh9d9k21d7i0b1jpnceb7kj.apps.googleusercontent.com',
    iosClientId: '427220706549-49cl75ehuhqph15gge0jmtuomvo7funn.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2bA0ReRwJShN2pOvGaUO7Y3m3tacFieI',
    appId: '1:427220706549:ios:1a75a39024324dee6e91bc',
    messagingSenderId: '427220706549',
    projectId: 'finalproject-30f96',
    storageBucket: 'finalproject-30f96.appspot.com',
    androidClientId: '427220706549-2u95imrvdkh9d9k21d7i0b1jpnceb7kj.apps.googleusercontent.com',
    iosClientId: '427220706549-49cl75ehuhqph15gge0jmtuomvo7funn.apps.googleusercontent.com',
    iosBundleId: 'com.example.depiFinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-_w2Hwuj1sWtQA3PbE8AzZK73l3Cb-g8',
    appId: '1:427220706549:web:ae18a334641ad70b6e91bc',
    messagingSenderId: '427220706549',
    projectId: 'finalproject-30f96',
    authDomain: 'finalproject-30f96.firebaseapp.com',
    storageBucket: 'finalproject-30f96.appspot.com',
    measurementId: 'G-WXJKETE5QE',
  );
}
